---
- name: Apache Server Setup
  hosts: all
  gather_facts: False
  tasks:
  
  - name: Install Apache
    yum:
      name: httpd
      state: present
      
  - name: Start Httpd and Make Persistent
    service:
      name: httpd
      state: started
      enabled: yes

  #- name: Putting index.html inside repo
  #  copy:
  #   src: index.html
  #    dest: /var/www/html/index.html
