---
- name: Post Provision Basic Configurations
  hosts: all
  tasks:

  - name: Create Base User Group
    group:
      name: default
      state: present

  - name: Create Support User
    user:
      name: support
      comment: Basic user
      uid: 1337
      group: default
      
  - name: Setting SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive
        
    - name: Installing Firewalld
      yum:
        name: firewalld
        state: latest
        
    - name: Check if Firewall is running
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Configuring Firewall Ports and Services
      firewalld:
        port: 10050/tcp
        permanent: yes
        state: enabled
                   
    - name: Configuring Firewall Ports and Services for HTTPS
      firewalld:
        service: https
        permanent: yes
        state: enabled
          
    - name: Configuring Firewall Ports and Services for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
    
    - name: Restart Firewall
      service:
        name: firewalld
        state: restarted